FROM golang:1.25-alpine

RUN apk add --no-cache git

# install air
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# cache dependencies
COPY go.mod go.sum ./
RUN go mod download

CMD ["air"]