database:
  dsn: "host=127.0.0.1 user=postgres password=123456 dbname=elearning port=5432 sslmode=disable"
jwt:
  access_token_secret: "your_access_token_secret"
  refresh_token_secret: "your_refresh_token_secret"
  access_token_expiration: "15m"
  refresh_token_expiration: "24h"
  issuer: "elearning-api" 